# Generated by Django 4.2.6 on 2023-10-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=200)),
                ('license_key', models.CharField(max_length=200, unique=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
